github.com:
    user: bprager
    git_protocol: https
    users:
        bprager:
            oauth_token: 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
    oauth_token: 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
