github.com:
    user: bprager
    git_protocol: https
    users:
        bprager:
            oauth_token: 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
    oauth_token: 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
