github.com:
    user: bprager
    git_protocol: https
    users:
        bprager:
            oauth_token: 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
    oauth_token: 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
