github.com:
    user: bprager
    git_protocol: https
    users:
        bprager:
            oauth_token: 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
    oauth_token: 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
